dist: bionic
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.7'
install:
- export PYTHON_VERSION=$(python -c "import sys;v = sys.version_info;print('%d.%d.%d' % (v[0], v[1], v[2]))")
- export PYTHON_VERSION_SHORT=$(python -c "import sys;v = sys.version_info;print('%d.%d' % (v[0], v[1]))")
- DIST_PACKAGES=/home/travis/virtualenv/python$PYTHON_VERSION/lib/python$PYTHON_VERSION_SHORT/site-packages
- python setup.py install
- cd ..
- pip install pytest coveralls
- git clone --depth=1 https://github.com/Nic30/hwt.git
- git clone --depth=1 https://github.com/Nic30/hwtLib.git
- cd hwt
- python setup.py install
- cd ../hwtLib
- python setup.py install
- cd ../ipCorePackager
- rm -rf $DIST_PACKAGES/ipCorePackager-*
- ln -s ipCorePackager $DIST_PACKAGES/ipCorePackager
script:
- coverage run --source=ipCorePackager setup.py test
deploy:
  provider: pypi
  user: nic30
  password:
    secure: oqou7l60AeRWex55gbodifRzNNElvTedB6RgdozBrBkexmF9sH4SxfvtWRk7Hj1K7EPqgoUvQWfiVlB7f7n1TrgHCcXLULNBLIbq+7meq6PdnE9Qv/GglqJhZra+8IHbeItANLCpcfKdaD96m/3cve4BwoPl5IcApgjeKZwTBkWjiaq19GoyOWRAiIeyA52Nx4e2N2MjxHOSjYE7FqHipR5IAgmmAokrW222jxthswlr6lkTJL+mZM0kI+fSf0F1RyzGGOjEChQ/VrGbkGe2ikdDKIn/aOSBE0p1LL1I3L5l30rAgJ6FNQBvLGgfyp6MCAyEakSOyi9nm4dVQ/svWS18ezbXQ4VF8Bh1mzp/iu99+kr8XBOwgM2rrDk557oJz7YSw5ieoKPlpmToxmLNHdLYRz6lT+8iQzbPVQ9jvC2zTzFuTBgJY0OoGyM62sOL0XsPQmeVjfAyVl7841GVRtlyKgzBVAJJ2RioH9Rvsz2bAVfxwf6z6vsMmKvxTWWW5wb2VA3b1dnm4PQvS5VyubK3SU0TzCdxwAydynfIEKl0ZsxCiibc+Sm01VXLyiRjcE1Bb2ZUBF6jR6BsGVs9mQvC2d4R+ziY5I4GuodMTR5BZDPQ9hVqEnsP1UAJ1zNdzAFI38f4LofkJ0RAGiUpAtuEMu8UXGjsU+X19Zjgyso=
  on:
    tags: true
    branch: master
after_success:
- coveralls
